### ISSUE TITLE
Support rendering through 'camera views'

### ISSUE THREAD

**Issue by pnstickne** [photonstorm/phaser3#3]
Currently the same approach as in Pixi is taken where the layers themselves act as a transformation up the root, which each being 'a parent' of the contained sprites - and there is some base layer (call it a stage or rootLayer or whatnot) that serves as the 'root' of the rendering tree.

It would be nice to have a separation of that for purposes of rendering a view - ie. instead of 'rendering a layer' it would 'render a view' (which contained a layer and a transformation *but is not a parent of the layer*). This would allow for really interesting split-screen as well as mini-maps (that don't necessarily inhabit world-space), etc.

Thus the view(s)/camera(s) would be *separate* of the world itself.

(This is different than render-to-texture, although the multicamera demo is pretty darn neat.)

**Comment by pjbaron** [comment]
As I merge the renderer with Phaser 2.4.4 I'm finding all the stuff that's missing from the renderer so far.  One big item is a separation of 'world' coordinates from local coordinates.  Currently everything is hierarchical so the x,y on a sprite is transformed by it's parent transform matrix (and so on up to the root).  I may just store the results of the transform each frame at each level, and that would give us nice 'world' coordinates - but I recall Phaser/PIXI ran into some problems with that eventually.

So (to get to the point) I'm interested in this idea of having a view level which is not a parent in the hierarchy (it might be a good reference frame for coordinates to be relative to).  Do you see any other advantages of having this view object be separate from the layers?

The current design (as you saw in the multi-camera demo) is based on the idea that you can draw from any point in the hierarchy, and everything below that point will turn up on the render-to-texture.  Then you can use those textures higher up as cameras, views, layers, whatever you want.  I'm not sure what advantages the View would have over this approach - except for this nice solid coordinate reference frame.

**Comment by pnstickne** [comment]
The world-physics/body transform is another .. fun issue, but I don't think it's tied to the rendering transformations themselves per se..

I've created a simple PR (oh goodness it is ugly) that shows that some of the state such as the parent transform can be pushed through the stack. Everything else is itself the same except for this decoupling of viewport - world layer. (I punted on passing through the render as well..)

Most games would only have one camera ("viewport") but with application of clipping and whatnot, and having cameras attached to different base layers, which could themselves be somewhere deeper in the tree..

**Comment by pnstickne** [comment]
For use-cases, split screens ( http://forums.pcsx2.net/attachment.php?aid=45892 , http://cdn.themis-media.com/media/global/images/galleries/display/50/50264.jpg ) and panning in games such as https://en.wikipedia.org/wiki/Worms_(series)

**Comment by pnstickne** [comment]
So, basically a camera/view *is* the root of a display graph, as determined by some layer, *as it is rendered* and separated from any logical parent.

**Comment by pjbaron** [comment]
Split screen is fully supported with the render-to-texture version already implemented (see multi-invaders demo).
Currently panning is supported by translating a layer which is larger than the draw area (or render-to-texture area) as seen in the scroll demo and the sci-fly demo.
I would also like to support panning via offsets to the immediate children of a layer which will give a very cheap (cpu) pan and be more suitable if the world is very large and has a tiling background for instance.  This is not essential because a layer is only a logical construct and doesn't exist as a texture until it is drawn, and then only the bits that fit the destination are drawn anyway... so a huge layer does not use a huge texture... but I think it will make neater code for things like the tiling backgrounds.
I think that possibly the strongest argument in favour of this is that a "camera" is a really easy concept for most people to understand and visualise how it will work.  However I'm not yet seeing a compelling argument in favour of disconnecting it from the draw hierarchy and adding that extra level of complexity (slight as it might be) to the draw system.
I believe it would be possible to simply rename a layer as 'camera', add a couple of 'camera-like' movement/zoom functions, and stay entirely within the existing hierarchy.
Date: Mon, 14 Sep 2015 04:04:20 -0700

**Comment by pnstickne** [comment]
Then let's go with that: a camera is a for separating - 'visualizing' - screen/renderer and world-space. Adding relevant view functions (mainly mapping a physical onto a logical) would be the next step.

I feel the problem with yet-another layer is precisely that it is still a parent (ie. stage) - it is this binding that a camera/view changes and because a camera/view is not a parent but is rather a window into a scene graph. It forms a M-1 (usually 1-1), not a 1-M.

The camera/view is also a severely restricted transformation in this manner; it can not appear as a child of anything, except insofar as it is associated with a screen (and input) - but can only be used as a final transformation/rendering. Thus this does not replace rtt and its uses for in-scene rendering; nor is it exclusive with such.

I was also hoping such a separation could be carried-through for physics and world-space concerns.
